version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "mbg"
    labels:
      - "gha"
      - "dependencies"
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/stan"
    schedule:
      interval: "daily"
    assignees:
      - "mbg"
    allow:
      - dependency-type: "direct"
    labels:
      - "npm"
      - "dependencies"
    rebase-strategy: "disabled"
