name: "Stack: Nightly Build"
description: "Build with the nightly Stack resolver"
author: "Michael B. Gale"
inputs:
  project-directory:
    required: false
    description: "The path to the root directory of the project (default: github.workspace)"
    default: ${{ github.workspace }}
  stack-version:
    required: false
    description: "The version of Stack to use (default: latest)"
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: "Install Stack"
      uses: haskell-actions/setup@v2
      id: install-haskell
      with:
        stack-no-global: true
        enable-stack: true
        stack-version: ${{ inputs.stack-version }}

    - name: Initialise stack.yaml with the nightly snapshot
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        rm -f stack.yaml && stack init --resolver nightly

    - name: Cache .stack folder
      id: cache-stack
      uses: actions/cache@v4
      with:
        path: ${{ steps.install-haskell.outputs.stack-root }}
        key: stack-nightly-${{ runner.os }}-${{ hashFiles(format('{0}/stack.yaml', inputs.project-directory)) }}-${{ hashFiles(format('{0}/*.cabal', inputs.project-directory)) }}
        restore-keys: |
          stack-nightly-${{ runner.os }}-${{ hashFiles(format('{0}/stack.yaml', inputs.project-directory)) }}-

    - name: Build and test with the nightly snapshot
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
