name: "Stan"

on:
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    working-directory: "stan"

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Run Stan
        uses: ./stan/
